name: Build, Test, and Coverage

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Run Behavioral Tests with Coverage
      run: |
        dotnet test CurrencyConverter.sln \
          --configuration Release \
          --no-build \
          --collect:"XPlat Code Coverage" \
          --results-directory ./TestResults \
          --logger "console;verbosity=normal" \
          --blame-hang \
          --blame-hang-timeout 5m

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate Coverage Report
      if: success() || failure()
      run: |
        reportgenerator \
          -reports:TestResults/**/coverage.cobertura.xml \
          -targetdir:coveragereport \
          -reporttypes:"HtmlInline_AzurePipelines;Cobertura"

    - name: Upload Coverage Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coveragereport