name: Build, Test, and Coverage

on:
  push:
    branches: [ master, develop, test-ci-cd ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Run Behavioral Tests with Coverage
      run: |
        dotnet test CurrencyConverter.sln \
          --configuration Release \
          --no-build \
          --collect:"XPlat Code Coverage" \
          --results-directory ./TestResults \
          --logger "console;verbosity=normal" \
          --blame-hang \
          --blame-hang-timeout 5m

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate Coverage Report
      run: |
        reportgenerator \
          -reports:TestResults/**/coverage.cobertura.xml \
          -targetdir:coveragereport \
          -reporttypes:"HtmlInline_AzurePipelines;Cobertura"

    - name: Install xmllint for coverage parsing
      run: sudo apt-get install -y libxml2-utils

    - name: Enforce Coverage Threshold
      run: |
        echo "Checking coverage threshold..."
        COVERAGE_FILE=$(find TestResults -name "coverage.cobertura.xml" | head -n 1)
        LINE_COVERAGE=$(xmllint --xpath "string(//coverage/@line-rate)" "$COVERAGE_FILE")
        LINE_COVERAGE_PERCENT=$(awk "BEGIN {printf \"%.2f\", $LINE_COVERAGE * 100}")

        echo "Line coverage: $LINE_COVERAGE_PERCENT%"
        THRESHOLD=75.0

        RESULT=$(awk "BEGIN {print ($LINE_COVERAGE_PERCENT >= $THRESHOLD) ? 1 : 0}")
        if [ "$RESULT" -ne 1 ]; then
          echo " Coverage $LINE_COVERAGE_PERCENT% is below threshold of $THRESHOLD%"
          exit 1
        else
          echo " Coverage $LINE_COVERAGE_PERCENT% meets the threshold of $THRESHOLD%"
        fi

    - name: Upload Coverage Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coveragereport